### ISSUE TITLE
Weekly scrum – March 15th 2021

### ISSUE THREAD

**Issue by oyenmwen** [oyenmwen/SurveyMonkey#17]

**Comment by oyenmwen** [comment]
what have I done this week? #21 #27 #30 
what will I do next week? I will implemented the show survey page
what is holding me back? I am so busy in other classes

**Comment by JulianMendoza** [comment]
What have I done this week? https://github.com/oyenmwen/SurveyMonkey/issues/8 https://github.com/oyenmwen/SurveyMonkey/issues/7 https://github.com/oyenmwen/SurveyMonkey/issues/20
What will I do next week? ajax for question submission
What is holding me back? N/A

**Comment by loisaleghe** [comment]
What have I done this week? #39 
what will i do next week? work on page to display survey result in a displayable manner
what is holding me back? workload from other classes + I'm currently not feeling too well

**Comment by Tamiod** [comment]
What have I done this week? #25 
What will I do next week? uml diagrams #26
What is holding me back? other courses

**Comment by GiuseppePapalia** [comment]
What have I done this week? #24 #41
What is holding me back? Working 60 hours a week outside of school
