### ISSUE TITLE
Weekly Scrum - March 22nd 2021

### ISSUE THREAD

**Issue by oyenmwen** [oyenmwen/SurveyMonkey#29]

**Comment by oyenmwen** [comment]
what have I done this week? #22 #33 #34
what will I do next week? More User Interfaced based features.
what is holding me back? Other academic obligations

**Comment by JulianMendoza** [comment]
What have I done this week? https://github.com/oyenmwen/SurveyMonkey/pull/24 https://github.com/oyenmwen/SurveyMonkey/pull/44
What will I do next week? Front-end animations, charts and look into project topic https://github.com/oyenmwen/SurveyMonkey/issues/43
What is holding me back? N/A

**Comment by Tamiod** [comment]
What have I done this week? #25  #26  #34
What will I do next week? Look into project topic, implement additional features and test more
What is holding me back? other courses

**Comment by loisaleghe** [comment]
What have I done this week? #39
what will i do next week? work on page to display survey result in a displayable manner
what is holding me back? workload from other classes + I'm currently not feeling too well

**Comment by GiuseppePapalia** [comment]
What have I done this week? #24 #41
What will I do next week? Finalize the results page
What is holding me back? Working 60 hours a week outside of school
