### ISSUE TITLE
Weekly scrum – March 8th 2021

### ISSUE THREAD

**Issue by oyenmwen** [oyenmwen/SurveyMonkey#4]
- what have I done this week? https://github.com/oyenmwen/SurveyMonkey/issues/3 https://github.com/oyenmwen/SurveyMonkey/issues/2
- what will I do next week? Currently undecided, perhaps something in the front end or back end.
- what is holding me back? Not applicable

**Comment by JulianMendoza** [comment]
What have I done this week? https://github.com/oyenmwen/SurveyMonkey/issues/10 https://github.com/oyenmwen/SurveyMonkey/issues/11 https://github.com/oyenmwen/SurveyMonkey/pull/12
What will I do next week? Work on infrastructure, looking at best practices/ways to use javascript.
What is holding me back? Not applicable

**Comment by loisaleghe** [comment]
What have I done this week #13 
What will I do next week? Keep updating the html and linking it to the database, practicing ways to improve my use of Javascript
What is holding me back? Not applicable

**Comment by Tamiod** [comment]
What have I done this week? #1 
What will I do next week? Keep testing to make sure they pass and update html
What is holding me back? Not applicable

**Comment by GiuseppePapalia** [comment]
What have I done this week? #8 
What will I do next week? Expand on the basic entities and test them
What is holding me back? Not applicable
