### ISSUE TITLE
Fix known bugs & results page layout

### ISSUE THREAD

**Issue by JulianMendoza** [oyenmwen/SurveyMonkey#43]
Passwords need to be used
Data needs to be reformed to be displayable for page layout

**Comment by oyenmwen** [comment]
> Passwords need to be used
> Data needs to be reformed to be displayable for page layout

Are passwords already not being used?

**Comment by JulianMendoza** [comment]
> > Passwords need to be used
> > Data needs to be reformed to be displayable for page layout
> 
> Are passwords already not being used?

Not currently used for displaying survey results the input field is there but we don't actually check before displaying the results
