### ISSUE TITLE
Weekly Scrum - March 29th 2021

### ISSUE THREAD

**Issue by JulianMendoza** [oyenmwen/SurveyMonkey#54]

**Comment by JulianMendoza** [comment]
What have I done this week? Finished https://github.com/oyenmwen/SurveyMonkey/issues/59 and https://github.com/oyenmwen/SurveyMonkey/issues/43
What will I do next week? Working on https://github.com/oyenmwen/SurveyMonkey/issues/60 https://github.com/oyenmwen/SurveyMonkey/issues/58
What is holding me back? School

**Comment by oyenmwen** [comment]
What have I done this week? #61 
What will I do next week? Continue to work on #61 & ReadMe
What is holding me back? School

**Comment by Tamiod** [comment]
What have I done this week? #51
What will I do next week? Finish up #51 and work on #65
What is holding me back? School

**Comment by GiuseppePapalia** [comment]
What have I done this week? progress on #62
What will I do next week? Finish up #62 
What is holding me back? 80 hour work weeks

**Comment by loisaleghe** [comment]
What have I done this week? #50 
What will I do next week? do #50 better 
What is holding me back? School
