### ISSUE TITLE
Weekly scrum – April 5th 2021

### ISSUE THREAD

**Issue by JulianMendoza** [oyenmwen/SurveyMonkey#55]

**Comment by JulianMendoza** [comment]
What have I done this week? Finished https://github.com/oyenmwen/SurveyMonkey/issues/60 PR: https://github.com/oyenmwen/SurveyMonkey/pull/48

**Comment by loisaleghe** [comment]
What have I done this week? #50 #52

**Comment by Tamiod** [comment]
what have I done this week? #51 #65 #64

**Comment by GiuseppePapalia** [comment]
what have I done this week? #62

**Comment by oyenmwen** [comment]
What have I done this week? #64 #66 
What will I do next week? Nothing
What is holding me back? School
